spring.application.name=Employee-Salary-Management
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5434/Company_Db
spring.datasource.username=postgres
spring.datasource.password=BazarutoIsland123!@#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
security.token.secret=employee123!@#